const {env}=process;
console.log(env);
// { NVM_RC_VERSION: '',
//   TERM_PROGRAM: 'Apple_Terminal',
//   NVM_CD_FLAGS: '',
//   TERM: 'xterm-256color',
//   SHELL: '/bin/bash',
//   TMPDIR: '/var/folders/9w/w84drcm51f52k53mdjgxj5v80000gn/T/',
//   Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.co5YgBW1nP/Render',
//   TERM_PROGRAM_VERSION: '388.1.1',
//   TERM_SESSION_ID: '4EAAF798-3C28-4D70-A0E5-347DC8EF62C1',
//   NVM_DIR: '/Users/yaya/nvm',
//   USER: 'yaya',
//   SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.nLsQH7yBOf/Listeners',
//   __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',
//   PATH: '/Users/yaya/desktop/mongodb/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yaya/Documents/mongodb-osx-x86_64-3.4.2/bin',
//   PWD: '/Users/yaya/desktop/project/learn/node-study/3-环境&调试',
//   LANG: 'zh_CN.UTF-8',
//   XPC_FLAGS: '0x0',
//   XPC_SERVICE_NAME: '0',
//   HOME: '/Users/yaya',
//   SHLVL: '1',
//   LOGNAME: 'yaya',
//   SECURITYSESSIONID: '186a7',
//   OLDPWD: '/Users/yaya/desktop/project/learn/node-study',
//   _: '/usr/local/bin/node' }
